name: Python Build and Test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print a message
        run: echo "Hello, this is the build and testing_layer workflow!"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests selenium

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

# this will work whever we call serial or paralel
      - name: Run Selenium Test
        run: python -m unittest testing_layer.api_tests.update_profile_test.profileTests.test_update_town_in_profile

      - name: Run passwordLogic testing_layer
        run: python -m unittest testing_layer.ui_tests.profile_changes_tests.profileChangeTests.test_run_grid_serial
#
#
#
