name: Python Build and Test
on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CHANNEL_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, this is the build and testing_layer workflow!"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests random2 selenium jira pytest pytest-html

      - name: Setup ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest

      - name: Setup FirefoxDriver
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run Tests and Generate Report
        run: |
          pytest main.py --html=report.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: report.html

      - name: Slack Notification
        if: always()
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#mhmdhuss_ci'

